version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bibu
      POSTGRES_PASSWORD: bibu
      POSTGRES_DB: mydb
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  django:
    container_name: django-app
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
