version: "3"
services:
  db:
    container_name: mydb
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bibu
      POSTGRES_PASSWORD: asad941215
      POSTGRES_DB: mydb

  django:
    container_name: django-app
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    container_name: my-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/
      - ./staticfiles:/usr/share/nginx/static/
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - db
      - django