# Generated by Django 5.1.3 on 2024-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invested',
            name='current_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invested',
            name='initial_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invested',
            name='input',
            field=models.PositiveIntegerField(),
        ),
    ]
