# Generated by Django 5.1.3 on 2024-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_total_invested_input_remove_user_invested_and_more'),
        ('stocks', '0003_stock_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invested',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='accounts_invested_uniq'),
        ),
    ]
