# Generated by Django 5.1.3 on 2024-12-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invested_accounts_invested_uniq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invested',
        ),
    ]
