name: build and deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connecting to ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            cd Foxstocks_Django_backend
            git fetch
            git pull origin main
            docker stop django-app
            docker compose build
            docker compose up -d django
            docker compose exec django python manage.py migrate
